### ISSUE TITLE
Unable to update Plugin

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress-pro-s3#23]
Error when trying to update S3 plugin. 

This is also impacting at least one other pro plugin [Github: https://github.com/humanmade/backupwordpress-pro-dropbox/issues/26]

![00000520](https://cloud.githubusercontent.com/assets/5481211/12796516/2e292896-ca8d-11e5-8880-4a61eb31b711.png)

**Comment by pdewouters** [comment]
handled by https://github.com/humanmade/Human-Made-website/issues/806
